# to run docker services  , to get the docker for each services we use mongo db 
services:
 fastapi:
    build:
     context: ..
     dockerfile: docker/minirag/Dockerfile
    container_name: fastapi
    ports: 
     - "8000:8000" 
    volumes:
      - fastapi_data:/app/assets
   
    networks:
     - backend 
    restart: always
    depends_on:
      pgvector:
       condition: service_healthy
    env_file:
      - ./env/.env.app
    
 
 nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
     - backend 
    restart: always
 pgvector:
    image: pgvector/pgvector:0.8.1-pg15 #repo name+ image tag name
    container_name: pgvector  # docker will run mongo service as a separated machine , the idea is that you need to connectg with that maschine and now mongo db is run that machine , i need to listen to this port 
    ports: 
     - "5432:5432" # mongodb run in machine on 27017
    volumes:
     - pgvector_data:/var/lib/postgresql/data # data path on my laptob : data path on the machine
   
    environment:
     - .env/.env.postgres
    networks:
     - backend # a containar network that allow all services to comunicate
    restart: always # if fail it restart automatic
    healthcheck: #كل 5 ثوانى هيسال البوست جريس شغال ولا لا و لو مش شغال هيرتراى ا
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s 
      timeout: 5s #عشان ينتظر الرد ف خلال 5 
      retries: 5
      start_period: 10s #start period wait postgress 10 sec prpaply he warming
# collect statics from postgres
 postgres-exporter: # collect data postgres
    image: prometheuscommunity/postgres-exporter:v0.17.1 #repo name+ image tag name
    container_name: postgres-exporter  # docker will run mongo service as a separated machine , the idea is that you need to connectg with that maschine and now mongo db is run that machine , i need to listen to this port 
    ports: 
      - "9187:9187" # mongodb run in machine on 27017
    env_file:
      - ./env/.env.postgres-exporter
    depends_on:
      - pgvector
    networks:
      - backend
    restart: always
 qdrant: #has build in exporter for metrics
    image: qdrant/qdrant:v1.13.6
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always
 prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus # approach 1- volume   private for docker unseen # docker volume
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # to allow us overwrite on default config,   config file to know from where you will take your metrices # local mounted volume
    networks:
      - backend
    restart: always
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
     - '--web.console.libraries=/etc/prometheus/console_libraries'
     - '--web.console.templates=/etc/prometheus/consoles'
     - '--web.enable-lifecycle' # allow me update  prometheus.yml while runtime

 grafana:
    image: grafana/grafana:11.6.0-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./env/.env.grafana
    depends_on:
      - prometheus
    networks:
      - backend
    restart: always

#metric for server / help get data about my host
 node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro # collect data on process in system , volumes عليها من ال  a mount بحددله يحط الحاجات دى فين بعدين 
      - /sys:/host/sys:ro # collect data on memory,disk
      - /:/rootfs:ro
    command:
     - '--path.procfs=/host/proc'
     - '--path.sysfs=/host/sys'
     - '--path.rootfs=/rootfs/sys'
     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' # regex to make path readable
    networks:
      - backend
    restart: always


networks:
 backend:
  driver: bridge

volumes:
  fastapi_data:
  pgvector_data:
  qdrant_data:
  prometheus_data:
  grafana_data: